server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning-plus
    username: postgres
    password: 224422
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

